name = "NavierStokes_Parallel"
uuid = "58fb019b-dfe5-4e9a-9999-96f48d80e751"
version = "0.2.0"
authors = ["Mark Owkes, Julian Fox"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FoldsThreads = "9c68100b-dfe1-47cf-94c8-95104e173443"
HYPRE = "b5ffcf37-a2bd-41ab-a3da-4bd9bc8ad771"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.8"
FLoops = "0.2"
FoldsThreads = "0.1"
Parameters = "0.12"
REPL = "1.11.0"
StatsBase = "0.34.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
